apiVersion: v1
kind: Service
metadata: 
  name: order-service
  namespace: {{ .Values.namespace }}
  labels:
    app: order-api
spec:
  selector:
    app: order-api
  ports:
  - name: order-service
    port: {{ .Values.ports.port }}
    targetPort: {{ .Values.ports.targetPort }}
  clusterIP: None
