apiVersion: v1
kind: Namespace
metadata:
  name: user-app
---
apiVersion: v1
kind: Namespace
metadata:
  name: book-app
---
apiVersion: v1
kind: Namespace
metadata:
  name: order-app
---
apiVersion: v1
kind: Namespace
metadata:
  name: frontend-shop
