apiVersion: v1
kind: Service
metadata:
  name: user-service
  namespace: {{ .Values.namespace }}
  labels:
    app: user-api
spec:
  selector:
    app: user-api
  ports:
  - name: user-service
    port: {{ .Values.ports.port }}
    targetPort: {{ .Values.ports.targetPort }}
  clusterIP: None
