apiVersion: v1
kind: Service
metadata:
  name: book-service
  namespace: {{ .Values.namespace }}
  labels:
    app: book-api
spec:
  selector:
    app: book-api
  ports:
  - name: book-service
    port: {{ .Values.ports.port }}
    targetPort: {{ .Values.ports.targetPort }}
  clusterIP: None
