apiVersion: v1
kind: Service
metadata:
  name: postgres-service
  namespace: {{ .Values.namespace }}
  labels:
    app: postgres-service
spec:
  selector:
    app: postgres-app
  ports:
  - name: postgres-port
    port: {{ .Values.service.port }}
    targetPort: {{ .Values.service.targetPort }}
  clusterIP: None

